Lots of changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,31 +34,34 @@ cd ${base}/rootfs
 binary="UNKNOWN"
 while ! test -d "${binary}"
 	do
-		echo "Select a binary base"; echo ""
+		echo "Select one binary base"; echo ""
 		find * -type d -mindepth 0 -maxdepth 0 -not -name common
-		echo ""; echo -n "binary base:"
+		echo ""; echo -n "Binary Base: "
 		read binary
 	done
 
 
-overlays=""; sep="";
-thisoverlay="UNKNOWN"
+overlays=""
 cd ${parent}
-while test "${thisoverlay}" = "UNKNOWN"
+while test -z "${overlays}"
 	do
-		echo "Select an overlay -> Current Overlays: ${overlays}"; echo ""
+		echo "Enter which overlays you want (space separated)"
+		echo ""
 
 		ls overlays
 
-		echo ""; echo -n "Add overlay [blank=done] :"
-		read thisoverlay
-		if test "${thisoverlay}" -a -d "overlays/${thisoverlay}"
-			then
-				overlays="${overlays}${sep}${thisoverlay}"; sep=" ";
-				thisoverlay="UNKNOWN"
-			fi
-	done
+		echo ""; echo -n "Overlays: "
+		read overlays
 
+		for ovr in ${overlays}
+		do
+			if ! test -d "overlays/${ovr}"
+				then
+					echo "ERR: could not find '${ovr}'"
+					overlays=""
+				fi
+		done
+	done
 
 {
 echo "# SlimLinux mkiso.cfg"
diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -41,8 +41,9 @@ if test "${cmd}" = "clean"
 		umount install_os.dd_mnt >/dev/null 2>&1
 		rm -f install_os.dd install_os.dd_mnt
 		rm -rf ROOT CONFIG DATA
-		rm -f ${rootfs} ${initrd} iso/isolinux/kernel *.iso ${base}/iso/install.cfg
+		rm -f ${rootfs} ${initrd} iso/isolinux/kernel *.iso ${isobase}/install.cfg
 		rm -f ${md5chk}
+		rm -rf ${isobase}/random
 		exit 0
 	fi
 
@@ -72,13 +73,6 @@ for ovr in ${overlays}
 
 iso="${binary}.iso"
 
-if test "${kernel}" -a -f "${parent}/kernel/${kernel}"
-	then
-		kernel="${parent}/kernel/${kernel}"
-	else
-		kernel="${parent}/kernel/kernel"
-	fi
-
 rm -f ${iso}
 
 if ! test -f ${initrd}
@@ -88,7 +82,7 @@ if ! test -f ${initrd}
 		umount install_os.dd_mnt >/dev/null 2>&1
 		rm -f install_os.dd install_os.dd_mnt
 
-		dd if=/dev/zero of=install_os.dd bs=1K count=8000 > /dev/null 2>&1
+		dd if=/dev/zero of=install_os.dd bs=1K count=8000 >/dev/null 2>&1
 		mke2fs -q -N 400 -m 0 -F install_os.dd
 		mkdir install_os.dd_mnt
 		mount -o loop install_os.dd install_os.dd_mnt
@@ -134,7 +128,8 @@ function add_depends()
 }
 
 
-function add_overlays()
+
+function capture_overlays()
 {
 	for ovr in ${overlays}
 		do
@@ -150,7 +145,12 @@ function add_overlays()
 				{ done[a[l]]="Y"; out=out _ " " _ a[l] }
 		print substr(out,2)
 		}')
+}
 
+
+
+function add_overlays()
+{
 	echo "Total overlays=${overlays}"
 
 	for ovr in ${overlays}
@@ -183,6 +183,22 @@ function add_overlays()
 		done
 }
 
+capture_overlays
+
+if test "${kernel}"
+	then
+		if ! test -f "${parent}/kernel/${kernel}"
+			then
+				echo "ERROR: kernel '${kernel}' not found"
+				ls -l ${parent}/kernel/${kernel}
+				exit 0
+			fi
+		kernel="${parent}/kernel/${kernel}"
+	else
+		kernel="${parent}/kernel/kernel"
+	fi
+
+echo "KERNEL: ${kernel}"
 
 
 if ! test -f ${rootfs}
@@ -225,6 +241,18 @@ if ! test -f ${rootfs}
 				cd ${parent}/DATA
 				tar Jcf ${datafs} .
 			fi
+	fi
+
+
+
+
+if ! test -d ${isobase}/random
+	then
+		mkdir ${isobase}/random
+		for x in 0 1 2 3 4 5 6 7 8 9
+		do
+			dd if=/dev/urandom of=${isobase}/random/${x}.rnd bs=1 count=512 >/dev/null 2>&1
+		done
 	fi
 
 
diff --git a/overlays/dns/rootfs/common/usr/scripts/make_dns_conf b/overlays/dns/rootfs/common/usr/scripts/make_dns_conf
--- a/overlays/dns/rootfs/common/usr/scripts/make_dns_conf
+++ b/overlays/dns/rootfs/common/usr/scripts/make_dns_conf
@@ -8,8 +8,9 @@
 
 . /usr/scripts/opts
 
+conf="/etc/dns.conf"
 tmp=/tmp/make_dns_conf_$$_$RANDOM
-dst="${dnsbase}/etc/dns.conf"
+dst="${dnsbase}${conf}"
 
 {
 echo 'options {
@@ -72,6 +73,7 @@ echo '
 
      directory "/var/dns";
      allow-update { none; };
+     allow-transfer { none; };
      notify no;
      max-udp-size 4096;
      edns-udp-size 4096;
@@ -214,6 +216,7 @@ zone "hostname.as112.arpa" {
 '
 fi
 
+
 if test "${dnsWithSlave}" = "Y"
 	then
 		mkdir -p ${dnsbase}/slave
@@ -228,21 +231,52 @@ if test "${dnsWithSlave}" = "Y"
 			gsub("/","_",file);
 			gsub(":","_",file);
 
-			printf "zone \"%s\" { type slave; file \"/slave/%s\"; masters {",a[1],file
+			printf "zone \"%s\" { type slave; file \"/slave/%s\";\n\tmasters {",a[1],file
 			for(l=2;l<=n;l++) printf "%s; ",a[l]
-			print "}; };"
+			print "}; };\n"
 
 			}' ${syscfg}
 	fi
+
+
+if test "${dnsWithMaster}" = "Y"
+	then
+		mkdir -p ${dnsbase}/master
+		chown nobody: ${dnsbase}/master
+
+		awk '/^dnsMaster=/ {
+			x=substr($0,index($0,"=")+1);
+			gsub("\"","",x);
+			n=split(x,a," ");
+
+			file=a[1];
+			gsub("/","_",file);
+			gsub(":","_",file);
+
+			iplist=""; adlist="";
+			for(l=2;l<=n;l++) {
+				iplist = iplist _ a[l] _ "; "
+				if (index(a[l],"/")==0) adlist = adlist _ a[l] _ "; "
+				}
+
+			printf "zone \"%s\" { type master; notify explicit; file \"/master/%s\";\n",a[1],file
+			if (iplist!="") printf "\tallow-transfer { %s };\n",iplist
+			if (adlist!="") printf "\talso-notify { %s };\n",adlist
+			print "\t};\n"
+
+			}' ${syscfg}
+	fi
+
+
 
 } > ${tmp}
 
 mv ${tmp} ${dst}
 
 
-if ! named-checkconf -t ${dnsbase}
+if ! named-checkconf -t ${dnsbase} ${conf}
 	then
-		logger -s -t "named-checkconf" "ERROR: dns.conf failed validation checks"
+		logger -s -t "named-checkconf" "ERROR: ${conf} failed validation checks"
 	else
 		killall -q -HUP named
 	fi
diff --git a/overlays/dns/rootfs/common/usr/scripts/start_dns b/overlays/dns/rootfs/common/usr/scripts/start_dns
--- a/overlays/dns/rootfs/common/usr/scripts/start_dns
+++ b/overlays/dns/rootfs/common/usr/scripts/start_dns
@@ -27,12 +27,19 @@ if test "${dnsWithAS112}" = "Y"
 			var/dns
 	fi
 
-/usr/scripts/make_dns_conf
-
-if ! named-checkconf -t ${dnsbase}
+conf="/etc/dns.conf"
+if test -f /opt/config/dns.conf
 	then
-		logger -s -t "start_dns" "dns.conf failed named-checkconf"
-		exec sleep 100
+		cp /opt/config/dns.conf ${dnsbase}${conf}
+		chown nobody: ${dnsbase}${conf}
+	else
+		/usr/scripts/make_dns_conf
 	fi
 
-exec /usr/sbin/named -u nobody -t ${dnsbase} -f
+if ! named-checkconf -t ${dnsbase} ${conf}
+	then
+		logger -s -t "start_dns" "dns.conf failed named-checkconf"
+		exec sleep 911
+	fi
+
+exec /usr/sbin/named -u nobody -t ${dnsbase} -f -c ${conf}
